version: '3.8'
name: farm-monitoring-app
services:
  fastapi:
    image: python:3.11-slim
    container_name: farm-fastapi
    volumes:
      - ./server:/app/server
      - ./datasets:/app/datasets
    working_dir: /app/server
    ports:
      - "8500:8500"
    command: >
      sh -c "pip install -r requirements.txt &&
             uvicorn main:app --host 0.0.0.0 --port 8500 --reload"
    environment:
      - PYTHONUNBUFFERED=1

  grafana:
    image: grafana/grafana:latest
    container_name: farm-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./client/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./client/datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./client:/var/lib/grafana/dashboards
    depends_on:
      - fastapi
